# for local development
version: '3.7'
services:
  db:
    container_name: mysql
    image: mysql:8.0.23
    volumes:
      - ./:/etc/mysql/conf.d/local.cnf
    environment:
      MYSQL_ROOT_PASSWORD: "1212"
      MYSQL_DATABASE: "travelwithme"

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: client/Dockerfile
  #   ports:
  #   - '8080:8080'
  #   volumes:
  #   - ./:/go/src/github.com/Dmytro-yakymuk/travelwithme/client
  #   command: /bin/sh -c "yarn serve"
  #     depends_on:
  #     - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./main
    volumes:
      - ./:/go/src/github.com/Dmytro-yakymuk/travelwithme
    ports:
      - "8000:8000"
    env_file: .env
    restart: always
    depends_on:
      - db